# nginx proxy address - http://172.17.0.1:8106

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  jirafeau:
    image: jirafeau/jirafeau:latest
    container_name: jirafeau-app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - jirafeau
    ports:
      - "8106:8106"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
    volumes:
      - ./rootfs/config/jirafeau:/config
      - ./rootfs/data/jirafeau:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8106"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  jirafeau:
    external: false
